blueprint:
  name: Philips Hue Dimmer Switch control
  description: 'Control lights with a Philips Hue Dimmer Switch. Set an action for each button. Note: You have to pick an action for each event. If you don’t want to react to an event, choose a Delay of 0sec.'
  domain: automation
  input:
    remote:
      name: Dimmer Switch Action sensor
      description: Select your entity that will control this
        automation.
      selector:
        entity:
          domain: sensor
    action_on_press:
      name: on-press
      description: select action to run when you press I
      default: []
      selector:
        action: {}
    action_off_press:
      name: off-press
      description: select action to run when you press O
      default: []
      selector:
        action: {}
    action_up_press:
      name: up-press
      description: select action to run when you press UP
      default: []
      selector:
        action: {}
    action_down_press:
      name: down-press
      description: select action to run when you press DOWN
      default: []
      selector:
        action: {}
    action_on_hold:
      name: on-hold
      description: select action to run when you hold I
      default: []
      selector:
        action: {}
    action_off_hold:
      name: off-hold
      description: select action to run when you hold O
      default: []
      selector:
        action: {}
    action_up_hold:
      name: up-hold
      description: select action to run when you hold UP
      default: []
      selector:
        action: {}
    action_down_hold:
      name: down-hold
      description: select action to run when you hold DOWN
      default: []
      selector:
        action: {}
mode: restart
trigger:
- platform: state
  entity_id: !input 'remote'
action:
- variables:
    command: '{{ trigger.to_state.attributes.action }}'
- choose:
  - conditions:
    - '{{ command == ''on-press'' }}'
    sequence: !input 'action_on_press'
  - conditions:
    - '{{ command == ''off-press'' }}'
    sequence: !input 'action_off_press'
  - conditions:
    - '{{ command == ''up-press'' }}'
    sequence: !input 'action_up_press'
  - conditions:
    - '{{ command == ''down-press'' }}'
    sequence: !input 'action_down_press'
  - conditions:
    - '{{ command == ''on-hold'' }}'
    sequence: !input 'action_on_hold'
  - conditions:
    - '{{ command == ''off-hold'' }}'
    sequence: !input 'action_off_hold'
  - conditions:
    - '{{ command == ''up-hold'' }}'
    sequence: !input 'action_up_hold'
  - conditions:
    - '{{ command == ''down-hold'' }}'
    sequence: !input 'action_down_hold'
  default: []
