blueprint:
  name: Zigbee2Mqtt Hue Dimmer Switch control v2
  description: ''
  domain: automation
  input:
    dimmer_action:
      name: Dimmer MQTT topic
      description: 'type in your Dimmer MQTT topic (i.e. zigbee2mqtt/Dimmer/action)'
      selector:
        text:
    action_on_press:
      name: on-press
      description: select action to run when you press I
      selector:
        action:
    action_off_press:
      name: off-press
      description: select action to run when you press O
      selector:
        action:
    action_up_press:
      name: up-press
      description: select action to run when you press UP
      selector:
        action:
    action_down_press:
      name: down-press
      description: select action to run when you press DOWN
      selector:
        action:
    action_on_hold:
      name: on-hold
      description: select action to run when you hold I
      selector:
        action:
    action_off_hold:
      name: off-hold
      description: select action to run when you hold O
      selector:
        action:
    action_up_hold:
      name: up-hold
      description: select action to run when you hold UP
      selector:
        action:
    action_down_hold:
      name: down-hold
      description: select action to run when you hold DOWN
      selector:
        action:

trigger:
  - platform: mqtt
    topic: !input dimmer_action
    payload: on-press
    id: dimmer_on
  - platform: mqtt
    topic: !input dimmer_action
    id: dimmer_off
    payload: off-press
  - platform: mqtt
    topic: !input dimmer_action
    id: dimmer_up
    payload: up-press
  - platform: mqtt
    topic: !input dimmer_action
    id: dimmer_down
    payload: down-press
  - platform: mqtt
    topic: !input dimmer_action
    id: dimmer_on_hold
    payload: on-hold
  - platform: mqtt
    topic: !input dimmer_action
    payload: off-hold
    id: dimmer_off_hold
  - platform: mqtt
    topic: !input dimmer_action
    id: dimmer_up_hold
    payload: up-hold
  - platform: mqtt
    topic: !input dimmer_action
    payload: down-hold
    id: dimmer_down_hold

action:
  - choose:
      - conditions:
          - condition: trigger
            id: dimmer_on
        sequence:
          !input action_on_press
      - conditions:
          - condition: trigger
            id: dimmer_off
        sequence:
          !input action_off_press
      - conditions:
          - condition: trigger
            id: dimmer_up
        sequence:
          !input action_up_press
      - conditions:
          - condition: trigger
            id: dimmer_down          
        sequence:
          !input action_down_press
      - conditions:
          - condition: trigger
            id: dimmer_on_hold
        sequence:
          !input action_on_hold
      - conditions:
          - condition: trigger
            id: dimmer_off_hold
        sequence:
          !input action_off_hold
      - conditions:
          - condition: trigger
            id: dimmer_up_hold
        sequence:
          !input action_up_hold
      - conditions:
          - condition: trigger
            id: dimmer_down_hold
        sequence:
          !input action_down_hold
    default: []
mode: restart
